function [predictions_test, mu_test] = ...
    rbd_mean_predict(hyp2, meanfunc, covfunc, likfunc, ...
    training_trajectories, training_output, test_trajectories, phiBetaMean)

    [mu_test, ~] = gp(  hyp2, @infGaussLik, meanfunc, covfunc, likfunc, ...
                        training_trajectories, training_output, test_trajectories);
    predictions_test = phiBetaMean + mu_test;
end